FROM ubuntu:20.04
ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get -y upgrade \
  && apt-get install -y -qq --no-install-recommends \
    libglvnd0 \
    libgl1 \
    libglx0 \
    libegl1 \
    libxext6 \
    libx11-6 \
    libgl1-mesa-glx \
    libgl1-mesa-dri \
    mesa-utils \
    ocl-icd-libopencl1 \
    opencl-headers \
    clinfo \
    glmark2 \
    git \
    wget \
    curl \
    xz-utils \
    g++ \
    libglib2.0.0 \
    libqt5x11extras5 \
    freeglut3-dev \
    initramfs-tools \
    ca-certificates \
    && rm -rf /var/lib/apt/lists/*
            
ARG AMD_DRIVER=amdgpu-pro-21.10-1247438-ubuntu-20.04.tar.xz
ARG AMD_DRIVER_URL=https://drivers.amd.com/drivers/linux
RUN mkdir -p /tmp/opencl-driver-amd
WORKDIR /tmp/opencl-driver-amd
RUN curl --referer $AMD_DRIVER_URL -O $AMD_DRIVER_URL/$AMD_DRIVER; \
    tar -Jxvf $AMD_DRIVER; \
    cd amdgpu-pro-*; \
    ./amdgpu-install --opencl=legacy,rocr --headless --no-dkms -y; \
    rm -rf /tmp/opencl-driver-amd;
    
ENV PATH="/root/miniconda3/bin:${PATH}"
ARG PATH="/root/miniconda3/bin:${PATH}"
RUN wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh; \
    mkdir /root/.conda; \
    bash Miniconda3-latest-Linux-x86_64.sh -b; \
    rm -f Miniconda3-latest-Linux-x86_64.sh; \
    echo "Successfully installed " conda --version; \
    conda init bash; \
    . /root/.bashrc; \
    conda create -n cellmodeller; \
    conda activate cellmodeller; \
    conda install python=3.8 pip; \
    pip install pyqt5;

WORKDIR /
RUN conda init bash; \
    . /root/.bashrc; \ 
    conda activate cellmodeller; \ 
    git clone https://github.com/HaseloffLab/CellModeller.git; \
    cd CellModeller && pip install -e .;
    
RUN echo 'conda activate cellmodeller \n\
python /CellModeller/Scripts/CellModellerGUI.py \n\
alias cmgui="python /CellModeller/Scripts/CellModellerGUI.py"' >> /root/.bashrc

RUN mkdir -p /etc/OpenCL/vendors && \
    echo "libamdocl64.so" > /etc/OpenCL/vendors/amdocl64.icd
RUN ln -s /usr/lib/x86_64-linux-gnu/libOpenCL.so.1 /usr/lib/libOpenCL.so
